-- Seed data for the breeds table.
-- Real NBAGR-recognised Indian breed names, origins, descriptions, and coat-colour categories.
-- coat_color is used by the colour-heuristic predictor in PredictionService (BLACK, REDDISH_BROWN, WHITE_GREY, GREY, SPOTTED_MIXED).
-- Runs fresh on every startup since the database is in-memory (see application.properties).

INSERT INTO breeds (id, name, type, origin, description, coat_color) VALUES
  (1, 'Gir', 'CATTLE', 'Gujarat', 'Zebu dairy breed known for distinctively curved horns and a domed forehead.', 'REDDISH_BROWN'),
  (2, 'Sahiwal', 'CATTLE', 'Punjab, Rajasthan', 'Heat-tolerant dairy breed with loose skin and a reddish-brown coat.', 'REDDISH_BROWN'),
  (3, 'Tharparkar', 'CATTLE', 'Rajasthan', 'Dual-purpose, drought-hardy breed of the Thar desert with a white-grey coat.', 'WHITE_GREY'),
  (4, 'Red Sindhi', 'CATTLE', 'Sindh region', 'Compact, heat-tolerant dairy breed with a deep red coat.', 'REDDISH_BROWN'),
  (5, 'Kankrej', 'CATTLE', 'Gujarat, Rajasthan', 'Large, grey draught-and-dairy breed with lyre-shaped horns.', 'GREY'),
  (6, 'Hariana', 'CATTLE', 'Haryana, Uttar Pradesh, Rajasthan', 'Dual-purpose white/grey breed valued for ploughing and moderate milk yield.', 'WHITE_GREY'),
  (7, 'Rathi', 'CATTLE', 'Rajasthan', 'Brown-and-white dairy breed from the Rajasthan-Punjab border area.', 'SPOTTED_MIXED'),
  (8, 'Ongole', 'CATTLE', 'Andhra Pradesh', 'Large, muscular breed prized for draught power and high-fat milk.', 'WHITE_GREY'),
  (9, 'Kangayam', 'CATTLE', 'Tamil Nadu', 'Sturdy draught breed known for speed and endurance in cart racing.', 'WHITE_GREY'),
  (10, 'Hallikar', 'CATTLE', 'Karnataka', 'Compact draught breed with long, backward-curving horns.', 'GREY'),
  (11, 'Amrit Mahal', 'CATTLE', 'Karnataka', 'Historic draught breed once bred for royal armies, known for stamina.', 'GREY'),
  (12, 'Khillari', 'CATTLE', 'Maharashtra, Karnataka', 'Fast, hardy draught breed with straight, pointed horns.', 'GREY'),
  (13, 'Deoni', 'CATTLE', 'Maharashtra, Karnataka', 'Dual-purpose spotted breed valued for both milk and draught work.', 'SPOTTED_MIXED'),
  (14, 'Gaolao', 'CATTLE', 'Maharashtra, Madhya Pradesh', 'Light, white draught breed known for quick trotting ability.', 'WHITE_GREY'),
  (15, 'Dangi', 'CATTLE', 'Maharashtra, Madhya Pradesh', 'White breed with red or black spots, suited to high-rainfall areas.', 'SPOTTED_MIXED'),
  (16, 'Nimari', 'CATTLE', 'Madhya Pradesh', 'Reddish-brown breed used mainly for draught power in central India.', 'REDDISH_BROWN'),
  (17, 'Malvi', 'CATTLE', 'Madhya Pradesh', 'Grey draught breed with a distinct black switch tail.', 'GREY'),
  (18, 'Kenkatha', 'CATTLE', 'Uttar Pradesh, Madhya Pradesh', 'Small, hardy draught breed adapted to rocky, dry terrain.', 'GREY'),
  (19, 'Kherigarh', 'CATTLE', 'Uttar Pradesh', 'Light, active draught breed with a compact body.', 'WHITE_GREY'),
  (20, 'Ponwar', 'CATTLE', 'Uttar Pradesh', 'Small hill-type breed used for light ploughing and carting.', 'GREY'),
  (21, 'Bachaur', 'CATTLE', 'Bihar', 'Medium dual-purpose breed of the Gandak river plains.', 'WHITE_GREY'),
  (22, 'Gangatiri', 'CATTLE', 'Uttar Pradesh, Bihar', 'Milch breed from the Ganga river belt with a compact build.', 'WHITE_GREY'),
  (23, 'Purnea', 'CATTLE', 'Bihar', 'Reddish, small-statured breed from the Purnea region.', 'REDDISH_BROWN'),
  (24, 'Siri', 'CATTLE', 'Sikkim, West Bengal', 'Hill breed of the eastern Himalayas, valued for hardiness at altitude.', 'BLACK'),
  (25, 'Lakhimi', 'CATTLE', 'Assam', 'Small breed of the Brahmaputra valley, kept mainly for milk and draught.', 'GREY'),
  (26, 'Khasi', 'CATTLE', 'Assam', 'North-eastern hill breed reared by Khasi and Jaintia communities.', 'GREY'),
  (27, 'Tho Tho', 'CATTLE', 'Nagaland', 'Small, hardy hill breed native to Nagaland.', 'GREY'),
  (28, 'Badri', 'CATTLE', 'Uttarakhand', 'Small Himalayan hill breed adapted to steep terrain.', 'GREY'),
  (29, 'Kumauni', 'CATTLE', 'Uttar Pradesh (hills)', 'Compact hill breed of the Kumaon region.', 'GREY'),
  (30, 'Ladakhi', 'CATTLE', 'Ladakh', 'High-altitude breed adapted to cold, thin mountain air.', 'BLACK'),
  (31, 'Belahi', 'CATTLE', 'Haryana, Chandigarh', 'Regional draught breed of the Haryana plains.', 'GREY'),
  (32, 'Hissar', 'CATTLE', 'Punjab (southern)', 'Draught breed related to Hariana, bred in the Hissar tract.', 'WHITE_GREY'),
  (33, 'Mewati', 'CATTLE', 'Rajasthan, Haryana, Uttar Pradesh', 'Dual-purpose breed similar to Hariana, from the Mewat region.', 'WHITE_GREY'),
  (34, 'Nagori', 'CATTLE', 'Rajasthan', 'Fast, elegant draught breed known for smart trotting bullocks.', 'WHITE_GREY'),
  (35, 'Sanchori', 'CATTLE', 'Rajasthan', 'Medium dairy breed of Jalore district, mostly white in colour.', 'WHITE_GREY'),
  (36, 'Kasaragod', 'CATTLE', 'Kerala', 'Small, hardy breed native to Kasaragod district.', 'WHITE_GREY'),
  (37, 'Vechur', 'CATTLE', 'Kerala', 'One of the world''s smallest cattle breeds, prized for rich, medicinal milk.', 'REDDISH_BROWN'),
  (38, 'Punganur', 'CATTLE', 'Andhra Pradesh', 'Miniature dwarf breed known for high butterfat milk despite small size.', 'WHITE_GREY'),
  (39, 'Krishna Valley', 'CATTLE', 'Karnataka', 'Large grey draught breed of the Krishna river basin.', 'GREY'),
  (40, 'Malnad Gidda', 'CATTLE', 'Karnataka', 'Small hill breed of the Western Ghats, valued for disease resistance.', 'BLACK'),
  (41, 'Bargur', 'CATTLE', 'Tamil Nadu', 'Agile breed from the Bargur forest tract, known for trotting ability.', 'SPOTTED_MIXED'),
  (42, 'Alambadi', 'CATTLE', 'Tamil Nadu', 'Grey draught breed native to the Alambadi tract of Tamil Nadu.', 'GREY'),
  (43, 'Umblachery', 'CATTLE', 'Tamil Nadu', 'Light-built breed adapted to marshy rice-field work.', 'WHITE_GREY'),
  (44, 'Pulikulam', 'CATTLE', 'Tamil Nadu', 'Small, hardy breed traditionally used in bull-taming sports.', 'GREY'),
  (45, 'Manapari', 'CATTLE', 'Tamil Nadu', 'Regional draught breed of southern Tamil Nadu.', 'GREY'),
  (46, 'Krishnagiri', 'CATTLE', 'Tamil Nadu', 'Draught breed of the Krishnagiri region.', 'GREY'),
  (47, 'Red Kandhari', 'CATTLE', 'Maharashtra', 'Black breed with a distinct red tinge, used for draught power.', 'BLACK'),
  (48, 'Khariar', 'CATTLE', 'Odisha', 'Small draught breed native to the Khariar region of Odisha.', 'GREY'),
  (49, 'Binjharpuri', 'CATTLE', 'Odisha', 'Compact dual-purpose breed of coastal Odisha.', 'GREY'),
  (50, 'Ghumusari', 'CATTLE', 'Odisha', 'Small hardy breed of the Ghumusar region.', 'GREY'),
  (51, 'Motu', 'CATTLE', 'Odisha, Chhattisgarh, Andhra Pradesh', 'Regional draught breed spread across eastern-central India.', 'GREY'),
  (52, 'Kosali', 'CATTLE', 'Chhattisgarh', 'Small dual-purpose breed of the Chhattisgarh plains.', 'GREY'),
  (53, 'Kathani', 'CATTLE', 'Maharashtra', 'Recently registered (2025) hardy regional breed of Maharashtra.', 'GREY'),
  (54, 'Murrah', 'BUFFALO', 'Haryana', 'India''s leading dairy buffalo breed, jet black with tightly curled horns.', 'BLACK'),
  (55, 'Nili-Ravi', 'BUFFALO', 'Punjab (Ravi river belt)', 'Recognisable by its wall eyes and curled horns, often with white markings.', 'BLACK'),
  (56, 'Jaffarabadi', 'BUFFALO', 'Gir forest, Gujarat', 'The heaviest buffalo breed, with massive horns and high-fat milk.', 'BLACK'),
  (57, 'Surti', 'BUFFALO', 'Gujarat', 'Medium-sized buffalo valued for high butterfat content in its milk.', 'GREY'),
  (58, 'Mehsana', 'BUFFALO', 'Gujarat', 'Cross-influenced breed between Murrah and Surti, efficient milk producer.', 'BLACK'),
  (59, 'Bhadawari', 'BUFFALO', 'Uttar Pradesh', 'Copper-grey breed prized for the highest butterfat content among Indian buffaloes.', 'GREY'),
  (60, 'Nagpuri', 'BUFFALO', 'Maharashtra', 'Black buffalo with white face and leg patches, used for milk and draught.', 'BLACK'),
  (61, 'Pandharpuri', 'BUFFALO', 'Maharashtra', 'Long, sword-shaped horns and lean build, adapted to Deccan conditions.', 'BLACK'),
  (62, 'Toda', 'BUFFALO', 'Tamil Nadu', 'Semi-wild hill breed reared by the Toda tribal community in the Nilgiris.', 'BLACK'),
  (63, 'Godavari', 'BUFFALO', 'Andhra Pradesh', 'River-belt breed of the Godavari delta, moderate milk yield.', 'BLACK'),
  (64, 'Kalahandi', 'BUFFALO', 'Odisha', 'Small, hardy buffalo breed of the Kalahandi plateau.', 'BLACK'),
  (65, 'Sambalpuri', 'BUFFALO', 'Odisha', 'Regional draught-and-milk breed of the Sambalpur region.', 'BLACK'),
  (66, 'Marathwadi', 'BUFFALO', 'Maharashtra', 'Compact regional breed of the Marathwada plains.', 'BLACK'),
  (67, 'Chilika', 'BUFFALO', 'Odisha', 'Breed native to the Chilika lake region, adapted to brackish wetlands.', 'BLACK'),
  (68, 'Banni', 'BUFFALO', 'Gujarat', 'Hardy breed of the Banni grasslands in Kutch, bred by Maldhari pastoralists.', 'BLACK'),
  (69, 'Manda', 'BUFFALO', 'Odisha', 'Small tribal breed reared in the hill tracts of southern Odisha.', 'BLACK'),
  (70, 'Jerangi', 'BUFFALO', 'Odisha', 'Regional buffalo breed of the Eastern Ghats hill tracts.', 'BLACK'),
  (71, 'Chhattisgarhi', 'BUFFALO', 'Chhattisgarh', 'Draught-oriented regional breed of the Chhattisgarh plains.', 'BLACK'),
  (72, 'Purnathadi', 'BUFFALO', 'Maharashtra', 'Recently registered (2022) regional breed of Maharashtra.', 'BLACK'),
  (73, 'Dharwadi', 'BUFFALO', 'Karnataka', 'Regional dual-purpose breed of the Dharwad plateau.', 'BLACK');

INSERT INTO breed_traits (breed_id, trait) VALUES
  (1, 'Curved horns'),
  (1, 'Reddish coat'),
  (1, 'High milk yield'),
  (2, 'Loose skin'),
  (2, 'Reddish-brown'),
  (2, 'Heat tolerant'),
  (3, 'White-grey coat'),
  (3, 'Drought hardy'),
  (3, 'Dual purpose'),
  (4, 'Compact build'),
  (4, 'Deep red coat'),
  (4, 'Heat tolerant'),
  (5, 'Lyre-shaped horns'),
  (5, 'Grey coat'),
  (5, 'Draught power'),
  (6, 'White-grey coat'),
  (6, 'Dual purpose'),
  (6, 'Good draught'),
  (7, 'Brown-white patches'),
  (7, 'Dairy type'),
  (7, 'Desert adapted'),
  (8, 'Large frame'),
  (8, 'White coat'),
  (8, 'Draught strength'),
  (9, 'Grey-white coat'),
  (9, 'Draught speed'),
  (9, 'Endurance'),
  (10, 'Long horns'),
  (10, 'Draught type'),
  (10, 'Agile'),
  (11, 'Grey coat'),
  (11, 'High stamina'),
  (11, 'Draught type'),
  (12, 'Grey coat'),
  (12, 'Fast draught'),
  (12, 'Straight horns'),
  (13, 'Black-white spots'),
  (13, 'Dual purpose'),
  (13, 'Hardy'),
  (14, 'White coat'),
  (14, 'Quick trotter'),
  (14, 'Draught type'),
  (15, 'Spotted coat'),
  (15, 'Rain tolerant'),
  (15, 'Dual purpose'),
  (16, 'Reddish-brown'),
  (16, 'Draught type'),
  (16, 'Compact'),
  (17, 'Grey coat'),
  (17, 'Black tail switch'),
  (17, 'Draught type'),
  (18, 'Small frame'),
  (18, 'Hardy'),
  (18, 'Draught type'),
  (19, 'White coat'),
  (19, 'Active'),
  (19, 'Draught type'),
  (20, 'Small frame'),
  (20, 'Hill adapted'),
  (20, 'Light draught'),
  (21, 'Grey-white coat'),
  (21, 'Dual purpose'),
  (21, 'Plains adapted'),
  (22, 'White coat'),
  (22, 'Milch type'),
  (22, 'River plains'),
  (23, 'Small frame'),
  (23, 'Reddish coat'),
  (23, 'Milch type'),
  (24, 'Hill adapted'),
  (24, 'Compact'),
  (24, 'Hardy'),
  (25, 'Small frame'),
  (25, 'Assam valley'),
  (25, 'Dual purpose'),
  (26, 'Hill adapted'),
  (26, 'Compact'),
  (26, 'Small frame'),
  (27, 'Hill adapted'),
  (27, 'Small frame'),
  (27, 'Hardy'),
  (28, 'Hill adapted'),
  (28, 'Small frame'),
  (28, 'Sure-footed'),
  (29, 'Hill adapted'),
  (29, 'Compact'),
  (29, 'Hardy'),
  (30, 'Cold adapted'),
  (30, 'High altitude'),
  (30, 'Hardy'),
  (31, 'Draught type'),
  (31, 'Plains adapted'),
  (31, 'Compact'),
  (32, 'Draught type'),
  (32, 'White-grey coat'),
  (32, 'Sturdy'),
  (33, 'Dual purpose'),
  (33, 'White-grey coat'),
  (33, 'Sturdy'),
  (34, 'White coat'),
  (34, 'Fast trotter'),
  (34, 'Draught type'),
  (35, 'White coat'),
  (35, 'Dairy type'),
  (35, 'Desert adapted'),
  (36, 'Small frame'),
  (36, 'Disease resistant'),
  (36, 'Grey-white coat'),
  (37, 'Dwarf breed'),
  (37, 'Rich milk'),
  (37, 'Kerala native'),
  (38, 'Dwarf breed'),
  (38, 'High butterfat'),
  (38, 'Compact'),
  (39, 'Grey coat'),
  (39, 'Large frame'),
  (39, 'Draught type'),
  (40, 'Small frame'),
  (40, 'Hill adapted'),
  (40, 'Disease resistant'),
  (41, 'Brown-white patches'),
  (41, 'Forest adapted'),
  (41, 'Agile'),
  (42, 'Grey coat'),
  (42, 'Draught type'),
  (42, 'Compact'),
  (43, 'Marsh adapted'),
  (43, 'Light frame'),
  (43, 'Draught type'),
  (44, 'Small frame'),
  (44, 'Hardy'),
  (44, 'Sporting breed'),
  (45, 'Draught type'),
  (45, 'Compact'),
  (45, 'Hardy'),
  (46, 'Draught type'),
  (46, 'Compact'),
  (46, 'Hardy'),
  (47, 'Black coat'),
  (47, 'Draught type'),
  (47, 'Sturdy'),
  (48, 'Small frame'),
  (48, 'Draught type'),
  (48, 'Hardy'),
  (49, 'Compact'),
  (49, 'Dual purpose'),
  (49, 'Hardy'),
  (50, 'Small frame'),
  (50, 'Hardy'),
  (50, 'Draught type'),
  (51, 'Draught type'),
  (51, 'Compact'),
  (51, 'Hardy'),
  (52, 'Small frame'),
  (52, 'Dual purpose'),
  (52, 'Hardy'),
  (53, 'Recently registered'),
  (53, 'Hardy'),
  (53, 'Regional breed'),
  (54, 'Tightly curled horns'),
  (54, 'Jet black'),
  (54, 'Top milk breed'),
  (55, 'Wall eyes'),
  (55, 'Curled horns'),
  (55, 'White markings'),
  (56, 'Massive horns'),
  (56, 'Heaviest buffalo breed'),
  (56, 'High fat milk'),
  (57, 'Sickle-shaped horns'),
  (57, 'Medium build'),
  (57, 'High butterfat milk'),
  (58, 'Black-grey coat'),
  (58, 'Efficient milker'),
  (58, 'Semi-arid adapted'),
  (59, 'Copper-grey coat'),
  (59, 'Highest butterfat'),
  (59, 'Ghee production'),
  (60, 'White facial patches'),
  (60, 'Black coat'),
  (60, 'Dual purpose'),
  (61, 'Sword-shaped horns'),
  (61, 'Lean build'),
  (61, 'Deccan adapted'),
  (62, 'Hill adapted'),
  (62, 'Semi-wild'),
  (62, 'Tribal breed'),
  (63, 'Godavari delta'),
  (63, 'Moderate yield'),
  (63, 'Regional breed'),
  (64, 'Small frame'),
  (64, 'Hardy'),
  (64, 'Plateau adapted'),
  (65, 'Dual purpose'),
  (65, 'Regional breed'),
  (65, 'Hardy'),
  (66, 'Compact build'),
  (66, 'Regional breed'),
  (66, 'Draught type'),
  (67, 'Wetland adapted'),
  (67, 'Regional breed'),
  (67, 'Hardy'),
  (68, 'Grassland adapted'),
  (68, 'Hardy'),
  (68, 'Pastoral breed'),
  (69, 'Hill adapted'),
  (69, 'Small frame'),
  (69, 'Tribal breed'),
  (70, 'Hill adapted'),
  (70, 'Regional breed'),
  (70, 'Hardy'),
  (71, 'Draught type'),
  (71, 'Regional breed'),
  (71, 'Hardy'),
  (72, 'Recently registered'),
  (72, 'Regional breed'),
  (72, 'Hardy'),
  (73, 'Dual purpose'),
  (73, 'Regional breed'),
  (73, 'Plateau adapted');

ALTER TABLE breeds ALTER COLUMN id RESTART WITH 74;
